import './globals.css'
import { Inter } from 'next/font/google'
import {UserState} from '../context/user/UserState'
import {Header} from '../comps/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
  <html lang="en">
    <body className={inter.className}>
     <UserState>
       <Header/>
       {children}
     </UserState>
    </body>
   </html>
  )
}
