import { Lora } from 'next/font/google'
import {UserState} from '../context/user/UserState'
import {Header} from '../comps/Header/Header'
import {GlobalStyle} from './extra.styled'
const lora = Lora({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
  <html lang="en">
    <body className={lora.className}>
    <GlobalStyle/>
     <UserState>
       <Header/>
       {children}
     </UserState>
    </body>
   </html>
  )
}
