export const GET_ITEMS = "GET_ITEMS"
export const START_LOADING = "START_LOADING"
export const END_LOADING = "END_LOADING"
export const ADD_ITEM = "ADD_ITEM"
export const UPDATE_ITEM = "INCREASE"
export const REMOVE_ITEM = "REMOVE_ITEM"
export const ERROR = "ERROR"
