'use client'
import {BoxState} from '../context/BoxState'

/*export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}*/
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
    <BoxState><body>{children}</body></BoxState>
    </html>
  )
}
