export const SET_CATEGORY = 'SET_CATEGORY'
export const SET_TYPE = 'SET_TYPE'
export const SET_PAGE = 'SET_PAGE'
export const SET_SEARCH = 'SET_SEARCH'
export const SET_REVERSE = 'SET_REVERSE'
export const RESET = 'RESET'
export const ERROR = 'ERROR'
